---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/index.html"
          highlight: "0-73"
        - file: "javascript/index.html"
          highlight: "14-14"
        - file: "javascript/index.html"
          highlight: "33-70"
        - file: "javascript/index.html"
          highlight: "35-43"
        - file: "javascript/index.html"
          highlight: "50-66"
        - file: "javascript/index.html"
          highlight: "69-69"
        - file: "javascript/client_app.js"
          highlight: "22-27"
        - file: "javascript/client_app.js"
          highlight: "36-112"
        - file: "javascript/client_app.js"
          highlight: "36-47"
        - file: "javascript/client_app.js"
          highlight: "58-102"
        - file: "javascript/client_app.js"
          highlight: "104-112"  