---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/createContactList.html"
          highlight: "0-44"
        - file: "javascript/createContactList.html"
          highlight: "13-15"
        - file: "javascript/createContactList.html"
          highlight: "16-29"
        - file: "javascript/createContactList.html"
          highlight: "31-40"
