---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/createCampaign.html"
          highlight: "0-69"
        - file: "javascript/createCampaign.html"
          highlight: "13-15"
        - file: "javascript/createCampaign.html"
          highlight: "16-34"
        - file: "javascript/createCampaign.html"
          highlight: "36-57"
        - file: "javascript/createCampaign.html"
          highlight: "59-67"
