---
analytics-conversation-aggregate-query:
    title: Querying Queue Historical Statistics
    description: See how to query historical statistics for a queue using the Analytics API.
    categories:
        - Analytics
architect-schedules:
    title: Evaluating Architect Schedules
    description: See how to query architect flows for their schedule and determine if an IVR is currently open or closed.
    categories:
        - Architect
oauth-implicit:
    title: OAuth Implicit Grant Login Flow
    description: Implicit grant login without a client library.
    categories:
        - OAuth
oauth-client-credentials:
    title: OAuth Client Credentials Login Flow
    description: Client credentials grant login without a client library.
    categories:
        - OAuth
oauth-auth-code:
    title: OAuth Authorization Code Grant Flow
    description: Authorization code grant login without a client library.
    categories:
        - OAuth
call-list-management:
    title: Dialer Call List Management
    description: Inserting records into a dialer call list and starting the dialer campaign.
    categories:
        - Dialer
create-campaign:
    title: Creating an Outbound Dialing Campaign
    description: Creating a campaign that can be run to place outbound calls.
    categories:
        - Dialer
create-contact-list:
    title: Creating an Outbound Dialing Contact List
    description: Creating a contact list for use with outbound dialing campaigns.
    categories:
        - Dialer
upload-contacts:
    title: Uploading Contacts to a Contact List
    description: Uploading contacts to an existing outbound dialing contact list.
    categories:
        - Dialer
upload-prompts:
    title: Uploading Architect Prompts
    description: Creating a prompt and uploading media
    categories:
        - Architect
presence:
    title: User Presence with Notifications
    description: Getting and setting the current user's presence and listening for changes.
    categories:
        - Status
        - Notifications
callbacks:
    title: Create Callback
    description: Using the Platform API to create callbacks.
    categories:
        - Callback
        - Conversations
calls:
    title: Call Handling
    description: Overview of basic call operations.
    categories:
        - Call
        - Conversations
chat-email-routing:
    title: 3rd Party Chat and Email Routing
    description: Introduction on how to route external objects through PureCloud ACD
    categories:
        - Chat
        - Email
external-contacts:
    title: Creating External Contacts
    description: Overview of creating External Contacts from a CSV file
    categories:
        - Contacts
client-app-sdk:
    title: Using Client App SDK
    description: See how to use URL Interpolation and send Toast using the Client App SDK.
    categories:
        - Architect
        - Notifications
queue-conversation-notification:
    title: Subscribe to Queue
    description: See how to subscribe to conversation notifications in a queue.
    categories:
        - Conversations
        - Notifications
premium-app-example-wizard:
    title: Premium App Wizard
    description: A template for premium app installer.
    categories:
        - Integrations
user-management:
    title: Creating and Updating a User
    description: Procedure for creating and then updating a user.
    categories:
        - Users
