---
ruby:
    displayName: Ruby
    steps:
        - file: "ruby/query.rb"
          highlight: "0-100"
        - file: "ruby/query.rb"
          highlight: "24-44"
        - file: "ruby/query.rb"
          highlight: "16-22"
        - file: "ruby/query.rb"
          highlight: "27-27"
        - file: "ruby/query.rb"
          highlight: "28-28"
        - file: "ruby/query.rb"
          highlight: "29-42"
        - file: "ruby/query.rb"
          highlight: "46-49"
        - file: "results.json"
          highlight: "1-100"
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/query.html"
          highlight: "0-100"
        - file: "javascript/query.html"
          highlight: "40-58"
        - file: "javascript/query.html"
          highlight: "26-32"
        - file: "javascript/query.html"
          highlight: "42-52"
        - file: "javascript/query.html"
          highlight: "43-43"
        - file: "javascript/query.html"
          highlight: "44-57"
        - file: "javascript/query.html"
          highlight: "60-64"
        - file: "results.json"
          highlight: "1-100"
