---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/uploadContacts.html"
          highlight: "0-60"
        - file: "javascript/uploadContacts.html"
          highlight: "14-16"
        - file: "javascript/uploadContacts.html"
          highlight: "17-25"
        - file: "javascript/uploadContacts.html"
          highlight: "46-56"
        - file: "javascript/uploadContacts.html"
          highlight: "27-44"
        - file: "javascript/uploadContacts.html"
          highlight: "0-60"
