---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/uploadContacts.html"
          highlight: "0-77"
        - file: "javascript/uploadContacts.html"
          highlight: "10-16"
        - file: "javascript/uploadContacts.html"
          highlight: "17-27"
        - file: "javascript/uploadContacts.html"
          highlight: "65-68"
        - file: "javascript/uploadContacts.html"
          highlight: "30-63"
        - file: "javascript/uploadContacts.html"
          highlight: "0-77"
