---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/index.html"
          highlight: "0-200"
        - file: "javascript/index.html"
          highlight: "34-50"
        - file: "javascript/index.html"
          highlight: "29-32"
        - file: "javascript/index.html"
          highlight: "53-95"
