---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/index.html"
          highlight: "0-133"
        - file: "javascript/index.html"
          highlight: "47-66"
        - file: "javascript/index.html"
          highlight: "68-76"
        - file: "javascript/index.html"
          highlight: "78-104"
        - file: "javascript/index.html"
          highlight: "113-123"
