---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/index.html"
          highlight: "0-151"
        - file: "javascript/index.html"
          highlight: "48-67"
        - file: "javascript/index.html"
          highlight: "69-84"
        - file: "javascript/index.html"
          highlight: "86-116"
        - file: "javascript/index.html"
          highlight: "125-135"
java:
    displayName: Java
    steps:
        - file: "java/src/com/inin/Main.java"
          highlight: "0-151"
        - file: "java/src/com/inin/Main.java"
          highlight: "31-49"
        - file: "java/src/com/inin/Main.java"
          highlight: "56-56"
        - file: "java/src/com/inin/Main.java"
          highlight: "56-56"
        - file: "java/src/com/inin/Main.java"
          highlight: "64-66"
