---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/index.html"
          highlight: "0-160"
        - file: "javascript/index.html"
          highlight: "45-65"
        - file: "javascript/index.html"
          highlight: "70-87"
        - file: "javascript/index.html"
          highlight: "103-126"
        - file: "javascript/index.html"
          highlight: "92-101"
java:
    displayName: Java
    steps:
        - file: "java/src/com/genesys/Main.java"
          highlight: "0-92"
        - file: "java/src/com/genesys/Main.java"
          highlight: "28-63"
        - file: "java/src/com/genesys/Main.java"
          highlight: "1-1"
        - file: "java/src/com/genesys/Main.java"
          highlight: "1-1"
        - file: "java/src/com/genesys/Main.java"
          highlight: "72-84"
