---
title: Premium App Wizard
description: A template for premium app installer.
categories:
- Integrations
steps:
- title: Introduction
  content: |
    This tutorial walks through the steps of implementing an installation flow that will configure the PureCloud environment for use by the Premium App.

    Common configurations that need to be done includes creating additional roles, creating groups, and creating additional instances of the app.

    For this project, we are going to use the Javascript PureCloud SDK and using Javascript ES6 coding standards.

    Other requirements:

    * A role that includes the premium app permission.
    * A premium app integration to access the installation web app.


- title: Creation of Javascript Object for Installation
  content: |
    There are three common PureCloud objects that need to be configured:

    * Roles
    * Groups
    * App Instances

    We're going to store all that we need in a simple Javascript Object to centralize and make it easier to modify in the future. This information could also be loaded from an external resource instead of being harcoded into the web app. 

    Objects created by the Installer are determined by the prefix on their name 
    'PREMIUM_APP_'. A safer option could be to store the ids of the generated PureCloud objects into an external database or storage.

- title: Set up Client App and determine Language and Environment
  content: |
    It is recommended for PureCloud apps to use the Client App SDK. This allows certain integrations to be implemented for example: Displaying an alert to the PureCloud UI, implementing lifecycle events, popping user profiles, and popping PureCloud help pages.

    We'll also determine the the environment (.com, .ie, .jp) and the language of the PureCloud user so the Premium App could use the correct authentication keys and language for the content.

- title: Authenticate through PureCloud
  content: |
    Before we can start making PureCloud API calls, we need to first authenticate to PureCloud. Different regions have different OAuth secrets so it must be determined before ateempting to authenticate.

- title: Getting User Information
  content: |
    It is a good practice to always start off geting the curent user's detail. This will make personalizing the page with the user's information better and will also allow double checking of any user setting or configuration.

- title: Validate Product Availability
  content: |
    As a precaution, make sure to check that the PureCloud org has the premium app feature enabled.

- title: Check if Existing
  content: |
    Before installation, it's recommended to first check if existing objects are still present. In this example, the web app will redirect the user to a different page instead of continuing with the installation. 

- title: Get existing Roles
  content: |
    In order to query Roles by prefix, we set the 'name' parameter to Prefix + '*' - whch serves as a wildcard for the search.

- title: Get Existing Groups
  content: |
    In querying groups, the API provides more parameters and we can use "START_WITH" to search for groups starting with a specific prefix.

- title: Get Existing Integration Instances
  content: |
    The API for listing integrations does not include any search/query parameters. We'll be getting a list of all integrations and manually filter the list to get the desired integrations. 

- title: Install Configurations
  content: |
    Installing all the configurations include 3 major steps:

    * Create Roles 
    * Create Groups
    * Create Integrations

    Each major step may contain more than one API call for setting up.

    First, we'll need to create instances of the APIs that we're going to need:

    * AuthorizationApi (for Roles)
    * GroupsApi (for Groups)
    * IntegrationsAPI (for Integrations)

    The installation will be performed in sequential order so we'll need to track the parallel calls using Promise arrays before moving to the next step.

    In this example, we're also resolving each API call to be displayed on the screen. We'll need arrays to contain the actual information that are needed for succeeding steps. 

- title: Create Roles
  content: |
    Creating roles require the role name and permissions assosciated with the role.

    After creating the role, it will be automatically assigned to the current user.

- title: Create Groups
  content: |
    To maintain the sequence of installation in this example, groups will only be created after the roles. This could be run in parallel since there are no data dependencies between the two.

    The current user will automatically be assign as the owner of the group.

- title: Create Integrations
  content: |
    In this example, integrations need to be created after groups because they can contain group filtering in their configuration.

    There are 3 steps in setting up the integration:

    1. Create an Integration (This API does not allow configuring the integration on creation)
    2. Configure the Integration (Name, URL, Group Filtering, etc.)
    3. Activate the Integration (By default Integrations are inactive)

- title: Redirect to App
  content: |
    After installation, the example should redirect to the Premium App Sample. 

    The Client App have no native way of knowing its own Inegration ID. It is recommended to not modify the URI but to have the default page redirect to either installation or the Premium App proper based on the status/existence of PureCloud objects.

- title: Clear Configuration
  content: |
    It is recommended to have a way to take down any existing configurations. This allows a new and clean installation of the Premium App.

    Things to note in this example:


    * Since we're tracking generated objects through the prefix, the original role and original integration instance created will not be deleted.
    * Groups that contain members, and roles that's assigned to users will not carry over to the new installation after deleting them.\

languages: 
  javascript:
    displayName: Javascript
    steps:
    - file: "javascript/wizard-app.js"
      highlight: "1-514"
    - file: "javascript/wizard-app.js"
      highlight: "11-70"
    - file: "javascript/wizard-app.js"
      highlight: "72-115"
    - file: "javascript/wizard-app.js"
      highlight: "117-126"
    - file: "javascript/wizard-app.js"
      highlight: "141-148"
    - file: "javascript/wizard-app.js"
      highlight: "151-168"
    - file: "javascript/wizard-app.js"
      highlight: "170-202"
    - file: "javascript/wizard-app.js"
      highlight: "292-302"
    - file: "javascript/wizard-app.js"
      highlight: "265-282"
    - file: "javascript/wizard-app.js"
      highlight: "312-330"
    - file: "javascript/wizard-app.js"
      highlight: "341-488"
    - file: "javascript/wizard-app.js"
      highlight: "360-387"
    - file: "javascript/wizard-app.js"
      highlight: "387-413"
    - file: "javascript/wizard-app.js"
      highlight: "413-460"
    - file: "javascript/index.html"
      highlight: "105-125"
    - file: "javascript/wizard-app.js"
      highlight: "203-263"
