---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/wizard-app.js"
          highlight: "1-649"
        - file: "javascript/config.js"
          highlight: "27-69"
        - file: "javascript/wizard-app.js"
          highlight: "568-633"
        - file: "javascript/wizard-app.js"
          highlight: "635-648"
        - file: "javascript/wizard-app.js"
          highlight: "44-53"
        - file: "javascript/wizard-app.js"
          highlight: "54-71"
        - file: "javascript/wizard-app.js"
          highlight: "72-105"
        - file: "javascript/wizard-app.js"
          highlight: "112-123"
        - file: "javascript/wizard-app.js"
          highlight: "192-210"
        - file: "javascript/wizard-app.js"
          highlight: "268-283"
        - file: "javascript/wizard-app.js"
          highlight: "480-505"
        - file: "javascript/wizard-app.js"
          highlight: "144-186"
        - file: "javascript/wizard-app.js"
          highlight: "231-261"
        - file: "javascript/wizard-app.js"
          highlight: "426-458"
        - file: "javascript/index.html"
          highlight: "105-125"
        - file: "javascript/wizard-app.js"
          highlight: "465-478"