---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/wizard-app.js"
          highlight: "1-514"
        - file: "javascript/wizard-app.js"
          highlight: "11-70"
        - file: "javascript/wizard-app.js"
          highlight: "72-115"
        - file: "javascript/wizard-app.js"
          highlight: "117-126"
        - file: "javascript/wizard-app.js"
          highlight: "141-148"
        - file: "javascript/wizard-app.js"
          highlight: "151-168"
        - file: "javascript/wizard-app.js"
          highlight: "170-202"
        - file: "javascript/wizard-app.js"
          highlight: "292-302"
        - file: "javascript/wizard-app.js"
          highlight: "265-282"
        - file: "javascript/wizard-app.js"
          highlight: "312-330"
        - file: "javascript/wizard-app.js"
          highlight: "341-488"
        - file: "javascript/wizard-app.js"
          highlight: "360-387"
        - file: "javascript/wizard-app.js"
          highlight: "387-413"
        - file: "javascript/wizard-app.js"
          highlight: "413-460"
        - file: "javascript/index.html"
          highlight: "105-125"
        - file: "javascript/wizard-app.js"
          highlight: "203-263"