---
nodejs:
    displayName: NodeJS
    steps:
        - file: "nodejs/isOpen.js"
          highlight: "0-100"
        - file: "nodejs/isOpen.js"
          highlight: "72-82"
        - file: "nodejs/isOpen.js"
          highlight: "27-61"
        - file: "nodejs/isOpen.js"
          highlight: "5-24"
