---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/index.html"
          highlight: "0-100"
        - file: "javascript/index.html"
          highlight: "30-40"
        - file: "javascript/index.html"
          highlight: "48-63"
