---
ruby:
    displayName: Ruby
    steps:
        - file: "ruby/script.rb"
          highlight: "0-100"
        - file: "ruby/script.rb"
          highlight: "3-6"
        - file: "ruby/script.rb"
          highlight: "9-19"
        - file: "ruby/script.rb"
          highlight: "22-23"          
nodejs:
    displayName: NodeJS
    steps:
        - file: "nodejs/index.js"
          highlight: "0-41"
        - file: "nodejs/index.js"
          highlight: "4-16"
        - file: "nodejs/index.js"
          highlight: "20-33"
        - file: "nodejs/index.js"
          highlight: "35-40"
