---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/calls.js"
          highlight: "0-200"
        - file: "javascript/calls.js"
          highlight: "49-62"
        - file: "javascript/calls.js"
          highlight: "65-74"
        - file: "javascript/calls.js"
          highlight: "76-104"
        - file: "javascript/calls.js"
          highlight: "121-142"
        - file: "javascript/calls.js"
          highlight: "144-161"
        - file: "javascript/calls.js"
          highlight: "107-119"
