---
javascript:
    displayName: Javascript
    steps:
        - file: "javascript/calls.js"
          highlight: "0-242"
        - file: "javascript/calls.js"
          highlight: "73-85"
        - file: "javascript/calls.js"
          highlight: "45-67"
        - file: "javascript/calls.js"
          highlight: "46-50"
        - file: "javascript/calls.js"
          highlight: "52-57"
        - file: "javascript/calls.js"
          highlight: "59-66"
        - file: "javascript/calls.js"
          highlight: "90-119"
        - file: "javascript/calls.js"
          highlight: "160-186"
        - file: "javascript/calls.js"
          highlight: "202-224"
        - file: "javascript/calls.js"
          highlight: "226-243"
        - file: "javascript/calls.js"
          highlight: "188-200"
