---
nodejs:
  displayName: NodeJS
  steps:
    - file: "nodejs/index.js"
      highlight: "0-100"
    - file: "nodejs/index.js"
      highlight: "7-13"
    - file: "nodejs/index.js"
      highlight: "16-28"
python:
  displayName: Python
  steps:
    - file: "python/user.py"
      highlight: "0-100"
    - file: "python/user.py"
      highlight: "9-15"
    - file: "python/user.py"
      highlight: "19-30"